on:
  workflow_dispatch:
    - name: ''
  schedule:
    - cron: '0 0 * * *'

name: fetch-data
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Fetch
        run: bash fetch-data.sh
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
